<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Exception handling and retry policies with Polly.</Description>
    <AssemblyTitle>RawRabbit.Enrichers.Polly</AssemblyTitle>
    <VersionPrefix>3.0.0</VersionPrefix>
    <Authors>pardahlman</Authors>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>RawRabbit.Enrichers.Polly</AssemblyName>
    <PackageId>RawRabbit.Enrichers.Polly</PackageId>
    <PackageTags>rabbitmq;rawrabbit;policy;polly</PackageTags>
    <PackageIconUrl>http://pardahlman.se/raw/icon.png</PackageIconUrl>
    <PackageProjectUrl>https://github.com/pardahlman/RawRabbit</PackageProjectUrl>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RawRabbit\RawRabbit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Polly" Version="8.5.0" />
    <PackageReference Include="Polly.Core" Version="8.5.0" />
  </ItemGroup>

</Project>
